source 'https://rubygems.org'

gem 'pg'
gem 'sinatra'

group :test, :development do
  gem 'capybara'
  gem 'pry'
  gem 'rerun', require: false
  gem 'rspec'
  gem 'rubocop'
  gem 'simplecov', require: false
  gem 'simplecov-console', require: false
end
